%% build the mex-cpp file by mex command
clc;

CERES_INCLUDE_DIRS =   {
    ['-I/usr/local/include'], ...
    ['-I/usr/include/eigen3'], ...
    ['-I/usr/include/usr/include'], ...
    ['-I/usr/include/suitesparse'], ...
};

CERES_LIBRARY_DIRS = {
    ['-L','/usr/local/lib'], ...
};

CERES_LIBRARIES = {
    ['/usr/local/lib/libceres.a'], ...
    ['-lcholmod'], ...
    ['-lglog'], ...
    ['-lcxsparse'], ...
    ['-llapack'], ...
    ['-lf77blas'], ...
    ['-lgomp'], ...
    ['-largeArrayDims'], ...
};

%% ======================================================================================== %%
disp('=====================================================================================');
disp('curveFittingCeresMex');
disp('=====================================================================================');
opts = {
    ['-DDEBUG '], ...
    % ['-D_GLIBCXX_USE_CXX11_ABI=0 '], ...
};
src = {
    ['cpp/curveFittingCeresMex.cpp'], ...
};

mex(...
    opts{:}, ...
    src{:}, ...
    CERES_INCLUDE_DIRS{:}, ...
    CERES_LIBRARY_DIRS{:}, ...
    CERES_LIBRARIES{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'curveFittingCeresMex'); 