% gen the calib_before leveling pose guess

clc;
close all;

if ~exist('data_root')
  data_root = '/media/bingo/SSD/multi_lidar_calib_data/prescan/scene_motion_plane_sync';
end

if ~exist('tools_matlab')
  tools_matlab = '/home/bingo/ethan/multi-lidar-calibration/tools/matlab';
end

addpath([tools_matlab '/' 'interface']);
addpath([tools_matlab '/' 'thirdParty/yaml']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~exist('calib_before_path')
  calib_before_path = 'calib_before';
end

if ~exist('calib_before_leveling_path')
  calib_before_leveling_path = 'calib_before_leveling';
end

% create the calib_before leveing path
calib_before_leveling_dir = sprintf('%s/%s', data_root, calib_before_leveling_path);
if ~exist(calib_before_leveling_dir)
  command = sprintf('mkdir -p %s', calib_before_leveling_dir);
  system(command);
end

% load the calib_before pose and gen the calib_before_leveling pose
% [roll pitch yaw x y z] [rad rad rad meters meters meters]
lidar_left_to_front_pose_before = loadPoseYaml(sprintf('%s/%s/lidar_1_to_2_estimated_6dof.txt', data_root, calib_before_path));
lidar_right_to_front_pose_before = loadPoseYaml(sprintf('%s/%s/lidar_3_to_2_estimated_6dof.txt', data_root, calib_before_path));
lidar_back_to_front_pose_before = loadPoseYaml(sprintf('%s/%s/lidar_4_to_2_estimated_6dof.txt', data_root, calib_before_path));

% [roll pitch yaw x y z]
% [roll pitch z] refers the roll, pitch and z offset to the ground
% [x y yaw] refers to the left, right and back refers to the front lidar
before_6dof_front_to_ground_front_filename = sprintf('%s/lidar_2_estimated_6dof.txt', calib_before_leveling_dir);
outputPoseYaml([0; ...
                0; ...
                0; ...
                0; ...
                0; ...
                0], ...
                before_6dof_front_to_ground_front_filename);

before_6dof_left_to_ground_front_filename = sprintf('%s/lidar_1_estimated_6dof.txt', calib_before_leveling_dir);
outputPoseYaml([0; ...
                0; ...
                lidar_left_to_front_pose_before(3); ...
                lidar_left_to_front_pose_before(4); ...
                lidar_left_to_front_pose_before(5); ...
                0], ...
                before_6dof_left_to_ground_front_filename);

before_6dof_right_to_ground_front_filename = sprintf('%s/lidar_3_estimated_6dof.txt', calib_before_leveling_dir);
outputPoseYaml([0; ...
                0; ...
                lidar_right_to_front_pose_before(3); ...
                lidar_right_to_front_pose_before(4); ...
                lidar_right_to_front_pose_before(5); ...
                0], ...
                before_6dof_right_to_ground_front_filename);

before_6dof_back_to_ground_front_filename = sprintf('%s/lidar_4_estimated_6dof.txt', calib_before_leveling_dir);
outputPoseYaml([0; ...
                0; ...
                lidar_back_to_front_pose_before(3); ...
                lidar_back_to_front_pose_before(4); ...
                lidar_back_to_front_pose_before(5); ...
                0], ...
                before_6dof_back_to_ground_front_filename);
