%% build the mex-cpp file by mex command
clc;

CERES_INCLUDE_DIRS =   {
    ['-I/usr/local/include'], ...
    ['-I/usr/include/eigen3'], ...
    ['-I/usr/include/usr/include'], ...
    ['-I/usr/include/suitesparse'], ...
};

CERES_LIBRARY_DIRS = {
    ['-L','/usr/local/lib'], ...
};

CERES_LIBRARIES = {
    ['/usr/local/lib/libceres.a'], ...
    ['-lcholmod'], ...
    ['-lglog'], ...
    ['-lcxsparse'], ...
    ['-llapack'], ...
    ['-lblas'], ...
    ['-lgomp'], ...
    ['-largeArrayDims'], ...
};

%% ======================================================================================== %%
disp('=====================================================================================');
disp('estimateExtrinsic2dMapDtMatchingCeresMex');
disp('=====================================================================================');
opts = {
    % ['-DDEBUG '], ...
};
src = {
    ['cpp/estimateExtrinsic2dMapDtMatchingCeresMex.cpp'], ...
};

mex(...
    opts{:}, ...
    src{:}, ...
    CERES_INCLUDE_DIRS{:}, ...
    CERES_LIBRARY_DIRS{:}, ...
    CERES_LIBRARIES{:}, ...
    '-outdir', ...
    './mex', ...
    '-output', ...
    'estimateExtrinsic2dMapDtMatchingCeresMex'); 